/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MechanicsRouteImport } from './routes/mechanics'
import { Route as OpticsRouteImport } from './routes/optics'
import { Route as MechanicsIndexRouteImport } from './routes/mechanics/index'
import { Route as MechanicsAccelerationRouteImport } from './routes/mechanics/acceleration'
import { Route as MechanicsMotionRouteImport } from './routes/mechanics/motion'
import { Route as OpticsIndexRouteImport } from './routes/optics/index'
import { Route as OpticsApparentDepthRouteImport } from './routes/optics/apparent-depth'
import { Route as OpticsLensesMirrorsRouteImport } from './routes/optics/lenses-mirrors'
import { Route as OpticsMagnifierRouteImport } from './routes/optics/magnifier'
import { Route as OpticsMirrorImageRouteImport } from './routes/optics/mirror-image'
import { Route as OpticsPaperImageRouteImport } from './routes/optics/paper-image'
import { Route as OpticsReflectionRouteImport } from './routes/optics/reflection'
import { Route as OpticsReflectionRefractionRouteImport } from './routes/optics/reflection-refraction'
import { Route as OpticsRefractionRouteImport } from './routes/optics/refraction'
import { Route as OpticsWalkingRowRouteImport } from './routes/optics/walking-row'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MechanicsRoute = MechanicsRouteImport.update({
  id: '/mechanics',
  path: '/mechanics',
  getParentRoute: () => rootRouteImport,
} as any)
const OpticsRoute = OpticsRouteImport.update({
  id: '/optics',
  path: '/optics',
  getParentRoute: () => rootRouteImport,
} as any)
const MechanicsIndexRoute = MechanicsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MechanicsRoute,
} as any)
const MechanicsAccelerationRoute = MechanicsAccelerationRouteImport.update({
  id: '/acceleration',
  path: '/acceleration',
  getParentRoute: () => MechanicsRoute,
} as any)
const MechanicsMotionRoute = MechanicsMotionRouteImport.update({
  id: '/motion',
  path: '/motion',
  getParentRoute: () => MechanicsRoute,
} as any)
const OpticsIndexRoute = OpticsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpticsRoute,
} as any)
const OpticsApparentDepthRoute = OpticsApparentDepthRouteImport.update({
  id: '/apparent-depth',
  path: '/apparent-depth',
  getParentRoute: () => OpticsRoute,
} as any)
const OpticsLensesMirrorsRoute = OpticsLensesMirrorsRouteImport.update({
  id: '/lenses-mirrors',
  path: '/lenses-mirrors',
  getParentRoute: () => OpticsRoute,
} as any)
const OpticsMagnifierRoute = OpticsMagnifierRouteImport.update({
  id: '/magnifier',
  path: '/magnifier',
  getParentRoute: () => OpticsRoute,
} as any)
const OpticsMirrorImageRoute = OpticsMirrorImageRouteImport.update({
  id: '/mirror-image',
  path: '/mirror-image',
  getParentRoute: () => OpticsRoute,
} as any)
const OpticsPaperImageRoute = OpticsPaperImageRouteImport.update({
  id: '/paper-image',
  path: '/paper-image',
  getParentRoute: () => OpticsRoute,
} as any)
const OpticsReflectionRoute = OpticsReflectionRouteImport.update({
  id: '/reflection',
  path: '/reflection',
  getParentRoute: () => OpticsRoute,
} as any)
const OpticsReflectionRefractionRoute =
  OpticsReflectionRefractionRouteImport.update({
    id: '/reflection-refraction',
    path: '/reflection-refraction',
    getParentRoute: () => OpticsRoute,
  } as any)
const OpticsRefractionRoute = OpticsRefractionRouteImport.update({
  id: '/refraction',
  path: '/refraction',
  getParentRoute: () => OpticsRoute,
} as any)
const OpticsWalkingRowRoute = OpticsWalkingRowRouteImport.update({
  id: '/walking-row',
  path: '/walking-row',
  getParentRoute: () => OpticsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mechanics': typeof MechanicsRouteWithChildren
  '/optics': typeof OpticsRouteWithChildren
  '/mechanics/acceleration': typeof MechanicsAccelerationRoute
  '/mechanics/motion': typeof MechanicsMotionRoute
  '/optics/apparent-depth': typeof OpticsApparentDepthRoute
  '/optics/lenses-mirrors': typeof OpticsLensesMirrorsRoute
  '/optics/magnifier': typeof OpticsMagnifierRoute
  '/optics/mirror-image': typeof OpticsMirrorImageRoute
  '/optics/paper-image': typeof OpticsPaperImageRoute
  '/optics/reflection': typeof OpticsReflectionRoute
  '/optics/reflection-refraction': typeof OpticsReflectionRefractionRoute
  '/optics/refraction': typeof OpticsRefractionRoute
  '/optics/walking-row': typeof OpticsWalkingRowRoute
  '/mechanics/': typeof MechanicsIndexRoute
  '/optics/': typeof OpticsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mechanics/acceleration': typeof MechanicsAccelerationRoute
  '/mechanics/motion': typeof MechanicsMotionRoute
  '/optics/apparent-depth': typeof OpticsApparentDepthRoute
  '/optics/lenses-mirrors': typeof OpticsLensesMirrorsRoute
  '/optics/magnifier': typeof OpticsMagnifierRoute
  '/optics/mirror-image': typeof OpticsMirrorImageRoute
  '/optics/paper-image': typeof OpticsPaperImageRoute
  '/optics/reflection': typeof OpticsReflectionRoute
  '/optics/reflection-refraction': typeof OpticsReflectionRefractionRoute
  '/optics/refraction': typeof OpticsRefractionRoute
  '/optics/walking-row': typeof OpticsWalkingRowRoute
  '/mechanics': typeof MechanicsIndexRoute
  '/optics': typeof OpticsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mechanics': typeof MechanicsRouteWithChildren
  '/optics': typeof OpticsRouteWithChildren
  '/mechanics/acceleration': typeof MechanicsAccelerationRoute
  '/mechanics/motion': typeof MechanicsMotionRoute
  '/optics/apparent-depth': typeof OpticsApparentDepthRoute
  '/optics/lenses-mirrors': typeof OpticsLensesMirrorsRoute
  '/optics/magnifier': typeof OpticsMagnifierRoute
  '/optics/mirror-image': typeof OpticsMirrorImageRoute
  '/optics/paper-image': typeof OpticsPaperImageRoute
  '/optics/reflection': typeof OpticsReflectionRoute
  '/optics/reflection-refraction': typeof OpticsReflectionRefractionRoute
  '/optics/refraction': typeof OpticsRefractionRoute
  '/optics/walking-row': typeof OpticsWalkingRowRoute
  '/mechanics/': typeof MechanicsIndexRoute
  '/optics/': typeof OpticsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mechanics'
    | '/optics'
    | '/mechanics/acceleration'
    | '/mechanics/motion'
    | '/optics/apparent-depth'
    | '/optics/lenses-mirrors'
    | '/optics/magnifier'
    | '/optics/mirror-image'
    | '/optics/paper-image'
    | '/optics/reflection'
    | '/optics/reflection-refraction'
    | '/optics/refraction'
    | '/optics/walking-row'
    | '/mechanics/'
    | '/optics/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mechanics/acceleration'
    | '/mechanics/motion'
    | '/optics/apparent-depth'
    | '/optics/lenses-mirrors'
    | '/optics/magnifier'
    | '/optics/mirror-image'
    | '/optics/paper-image'
    | '/optics/reflection'
    | '/optics/reflection-refraction'
    | '/optics/refraction'
    | '/optics/walking-row'
    | '/mechanics'
    | '/optics'
  id:
    | '__root__'
    | '/'
    | '/mechanics'
    | '/optics'
    | '/mechanics/acceleration'
    | '/mechanics/motion'
    | '/optics/apparent-depth'
    | '/optics/lenses-mirrors'
    | '/optics/magnifier'
    | '/optics/mirror-image'
    | '/optics/paper-image'
    | '/optics/reflection'
    | '/optics/reflection-refraction'
    | '/optics/refraction'
    | '/optics/walking-row'
    | '/mechanics/'
    | '/optics/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MechanicsRoute: typeof MechanicsRouteWithChildren
  OpticsRoute: typeof OpticsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mechanics': {
      id: '/mechanics'
      path: '/mechanics'
      fullPath: '/mechanics'
      preLoaderRoute: typeof MechanicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/optics': {
      id: '/optics'
      path: '/optics'
      fullPath: '/optics'
      preLoaderRoute: typeof OpticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mechanics/': {
      id: '/mechanics/'
      path: '/'
      fullPath: '/mechanics/'
      preLoaderRoute: typeof MechanicsIndexRouteImport
      parentRoute: typeof MechanicsRoute
    }
    '/mechanics/acceleration': {
      id: '/mechanics/acceleration'
      path: '/acceleration'
      fullPath: '/mechanics/acceleration'
      preLoaderRoute: typeof MechanicsAccelerationRouteImport
      parentRoute: typeof MechanicsRoute
    }
    '/mechanics/motion': {
      id: '/mechanics/motion'
      path: '/motion'
      fullPath: '/mechanics/motion'
      preLoaderRoute: typeof MechanicsMotionRouteImport
      parentRoute: typeof MechanicsRoute
    }
    '/optics/': {
      id: '/optics/'
      path: '/'
      fullPath: '/optics/'
      preLoaderRoute: typeof OpticsIndexRouteImport
      parentRoute: typeof OpticsRoute
    }
    '/optics/apparent-depth': {
      id: '/optics/apparent-depth'
      path: '/apparent-depth'
      fullPath: '/optics/apparent-depth'
      preLoaderRoute: typeof OpticsApparentDepthRouteImport
      parentRoute: typeof OpticsRoute
    }
    '/optics/lenses-mirrors': {
      id: '/optics/lenses-mirrors'
      path: '/lenses-mirrors'
      fullPath: '/optics/lenses-mirrors'
      preLoaderRoute: typeof OpticsLensesMirrorsRouteImport
      parentRoute: typeof OpticsRoute
    }
    '/optics/magnifier': {
      id: '/optics/magnifier'
      path: '/magnifier'
      fullPath: '/optics/magnifier'
      preLoaderRoute: typeof OpticsMagnifierRouteImport
      parentRoute: typeof OpticsRoute
    }
    '/optics/mirror-image': {
      id: '/optics/mirror-image'
      path: '/mirror-image'
      fullPath: '/optics/mirror-image'
      preLoaderRoute: typeof OpticsMirrorImageRouteImport
      parentRoute: typeof OpticsRoute
    }
    '/optics/paper-image': {
      id: '/optics/paper-image'
      path: '/paper-image'
      fullPath: '/optics/paper-image'
      preLoaderRoute: typeof OpticsPaperImageRouteImport
      parentRoute: typeof OpticsRoute
    }
    '/optics/reflection': {
      id: '/optics/reflection'
      path: '/reflection'
      fullPath: '/optics/reflection'
      preLoaderRoute: typeof OpticsReflectionRouteImport
      parentRoute: typeof OpticsRoute
    }
    '/optics/reflection-refraction': {
      id: '/optics/reflection-refraction'
      path: '/reflection-refraction'
      fullPath: '/optics/reflection-refraction'
      preLoaderRoute: typeof OpticsReflectionRefractionRouteImport
      parentRoute: typeof OpticsRoute
    }
    '/optics/refraction': {
      id: '/optics/refraction'
      path: '/refraction'
      fullPath: '/optics/refraction'
      preLoaderRoute: typeof OpticsRefractionRouteImport
      parentRoute: typeof OpticsRoute
    }
    '/optics/walking-row': {
      id: '/optics/walking-row'
      path: '/walking-row'
      fullPath: '/optics/walking-row'
      preLoaderRoute: typeof OpticsWalkingRowRouteImport
      parentRoute: typeof OpticsRoute
    }
  }
}

interface MechanicsRouteChildren {
  MechanicsAccelerationRoute: typeof MechanicsAccelerationRoute
  MechanicsMotionRoute: typeof MechanicsMotionRoute
  MechanicsIndexRoute: typeof MechanicsIndexRoute
}

const MechanicsRouteChildren: MechanicsRouteChildren = {
  MechanicsAccelerationRoute: MechanicsAccelerationRoute,
  MechanicsMotionRoute: MechanicsMotionRoute,
  MechanicsIndexRoute: MechanicsIndexRoute,
}

const MechanicsRouteWithChildren = MechanicsRoute._addFileChildren(
  MechanicsRouteChildren,
)

interface OpticsRouteChildren {
  OpticsApparentDepthRoute: typeof OpticsApparentDepthRoute
  OpticsLensesMirrorsRoute: typeof OpticsLensesMirrorsRoute
  OpticsMagnifierRoute: typeof OpticsMagnifierRoute
  OpticsMirrorImageRoute: typeof OpticsMirrorImageRoute
  OpticsPaperImageRoute: typeof OpticsPaperImageRoute
  OpticsReflectionRoute: typeof OpticsReflectionRoute
  OpticsReflectionRefractionRoute: typeof OpticsReflectionRefractionRoute
  OpticsRefractionRoute: typeof OpticsRefractionRoute
  OpticsWalkingRowRoute: typeof OpticsWalkingRowRoute
  OpticsIndexRoute: typeof OpticsIndexRoute
}

const OpticsRouteChildren: OpticsRouteChildren = {
  OpticsApparentDepthRoute: OpticsApparentDepthRoute,
  OpticsLensesMirrorsRoute: OpticsLensesMirrorsRoute,
  OpticsMagnifierRoute: OpticsMagnifierRoute,
  OpticsMirrorImageRoute: OpticsMirrorImageRoute,
  OpticsPaperImageRoute: OpticsPaperImageRoute,
  OpticsReflectionRoute: OpticsReflectionRoute,
  OpticsReflectionRefractionRoute: OpticsReflectionRefractionRoute,
  OpticsRefractionRoute: OpticsRefractionRoute,
  OpticsWalkingRowRoute: OpticsWalkingRowRoute,
  OpticsIndexRoute: OpticsIndexRoute,
}

const OpticsRouteWithChildren =
  OpticsRoute._addFileChildren(OpticsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MechanicsRoute: MechanicsRouteWithChildren,
  OpticsRoute: OpticsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
